### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailIndexer#1]
Hey @andrewlalis, 

For my MSc internship I'll be using your search engine to classify emails. 
I started messing around with your tool a little (which really works quite nice!), however, could not figure out how to add (custom) tags to emails.

The dataset I received from Mohamed already contained three tags (_architecture_, _info_, and _knowledge_), so I can assign those, but those are (probably) not the ones I'll use in my research.
Could you explain how I add these in your tool? If that's not possible yet, I'll find another way, but it's easier to do it inside the GUI.

Thanks!

**Comment by wmeijer221** [comment]
Whoops, just realized I posted this on the wrong repository. I meant to ask this in the email browser.

**Comment by andrewlalis** [comment]
> Hey @andrewlalis, 
> 
> For my MSc internship I'll be using your search engine to classify emails. 
> I started messing around with your tool a little (which really works quite nice!), however, could not figure out how to add (custom) tags to emails.
> 
> The dataset I received from Mohamed already contained three tags (_architecture_, _info_, and _knowledge_), so I can assign those, but those are (probably) not the ones I'll use in my research.
> Could you explain how I add these in your tool? If that's not possible yet, I'll find another way, but it's easier to do it inside the GUI.
> 
> Thanks!

Hey @wmeijer221 ,

You can add custom tags by simply typing in the text field portion of the tag selection box that you already used for tagging emails with the pre-defined tags.

Conversely, a tag just disappears once there exist no emails with that tag (since tags are simply just strings attached to an email).
