### ISSUE TITLE
Bug: EmailRepository.loadRepliesRecursive loads too many emails.

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailIndexer#3]
I've been working on an export method to PDF for lucene search results in the EmailBrowser. Since there was an implementation for plain-text already, I followed that as a template. In the plain text version, ``EmailRepository.loadRepliesRecursive`` is used to load a complete mailing thread. However, I believe that the current implementation loads the same emails multiple times, resulting in gigantic exports for long mailing threads.

**Comment by andrewlalis** [comment]
Do you mean that for a given email, it might contain duplicate replies?

**Comment by wmeijer221** [comment]
yes

**Comment by andrewlalis** [comment]
I'm closing this now that I have actually completely removed this method from the `EmailRepository` in the latest version.
