### ISSUE TITLE
Bug: Query export fails with high result count.

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailIndexer#9]
I wrote a query that yields +- 1100 results, which I want to export to ``.csv`` format. However, because the ``maxClauseCount`` is set to 1024 the export fails. This also happens when you set the maximum result count to lower than that. The image shows the export result.

A simple solution is to split up the query into chunks, but it would be nice if this issue is resolved in some future. 

I used version 2.7.0 of the browser app.

**Comment by andrewlalis** [comment]
Sorry, but I don't really know what you're referring to. By `maxClauseCount`, do you mean `maxResultCount` in the `ExportParameters` class, or something else? In fact, the only instance of the `1024` integer literal in the project is where I define the `SUBJECT VARCHAR(1024)` column of the `EMAIL` table.

Also, you said that "the image shows the export result", but I don't know if you meant to upload an image with this issue or somewhere else?

**Comment by wmeijer221** [comment]
Oh wait; I see what happened! 
Apparently lucenesearch has a cap on the number of clauses inside your query (1024), and throws an error if you exceed this. 
The error message in the export panel is just ambiguous; my bad.
